Allow configuration of repository factory (as per ORM module)
doctrine/DoctrineMongoODMModule pull request #176
Opened 2016-10-25 16:16 UTC by Bombdog

The need has arisen for me to inject a caching service into my repositories. If found some examples for the ORM module but I noticed that the equivalent is not available for the ODM module.

http://blog.tomhanderson.com/2016/01/dependency-injection-in-doctrine.html

I checked and the RepositoryFactory was added in to ODM on 28th March 2015. It would be nice to be able to use this.

https://github.com/doctrine/mongodb-odm/pull/892

2016-10-25 17:12 UTC, malarzm commented
FWIW the feature is available in all stable versions

2017-02-10 09:58 UTC, Bombdog commented
Sorry I should have used a branch rather than master. Do I need to do anything? This is rather old :-(

2017-02-10 11:42 UTC, alcaeus commented
@Bombdog you don't need to do anything, I'll cherry-pick the commit manually should need be.

2017-02-12 06:43 UTC, alcaeus commented
@Bombdog can you add tests for the new config option? Thanks!

2017-02-20 16:57 UTC, Bombdog commented
@alcaeus I added an additional assertion to the existing configuration factory test. Followed the style of what was there already.

2017-02-20 19:09 UTC, alcaeus requested changes

2017-02-20 19:09 UTC, alcaeus commented on src/DoctrineMongoODMModule/Options/Configuration.php
> +    public function getRepositoryFactory() {
Apparently we don't have automatic checks here, but the opening curly brace goes in its own line for functions (see PSR-2).

2017-02-20 19:09 UTC, alcaeus commented on src/DoctrineMongoODMModule/Options/Configuration.php
> +    public function setRepositoryFactory($repositoryFactory) {
Curly brace again.

2017-02-20 19:09 UTC, alcaeus commented on src/DoctrineMongoODMModule/Service/ConfigurationFactory.php
> +        if ($repositoryFactory = $options->getRepositoryFactory()){
Missing a space before the curly brace

2017-02-21 10:58 UTC, Bombdog commented
Ok I just amended, cheers

2017-02-22 20:08 UTC, alcaeus approved these changes

2017-02-22 20:08 UTC, merged

2017-02-22 20:08 UTC, alcaeus commented
Thanks, @Bombdog!