Added .doctrine-project.json
doctrine/DoctrineMongoODMModule pull request #228
Opened 2020-10-31 21:24 UTC by TomHAnderson

With this PR I think we're ready to drop the master branch.

2020-10-31 22:04 UTC, SenseException requested changes

2020-10-31 22:04 UTC, SenseException commented on .doctrine-project.json
> +        "3.0.x"
```suggestion
        "stable"
```

2020-10-31 22:04 UTC, SenseException commented on .doctrine-project.json
> +      ]
```suggestion
      "maintained":false
```

2020-10-31 22:18 UTC, TomHAnderson commented on .doctrine-project.json
> +        "3.0.x"
Removed 3.0.x allias

2020-11-01 11:03 UTC, greg0ire approved these changes

2020-11-01 19:04 UTC, SenseException approved these changes

2020-11-01 20:11 UTC, merged