Prepare docs for Doctrine website
doctrine/DoctrineMongoODMModule pull request #230
Opened 2021-10-20 15:27 UTC by driehle

2021-10-20 21:19 UTC, SenseException requested changes

2021-10-20 21:19 UTC, SenseException commented on docs/en/development.rst
> +   docker-compose run --rm php composer cs-check src test config
Maybe the code highlighting for bash would look nice here.

2021-10-21 01:36 UTC, TomHAnderson requested changes

2021-10-21 01:36 UTC, TomHAnderson commented on docs/en/usage.rst
> +Access the Doctrine command line as following
`...as follows`

2021-10-21 01:36 UTC, TomHAnderson commented on docs/en/usage.rst
> +Service Locator
`Service Manager`

Service locator is no longer in the vernacular for this context.

2021-10-21 01:36 UTC, TomHAnderson commented on docs/en/user-guide.rst
> +install composer via ``curl -s http://getcomposer.org/installer | php``
Capitalize `Install`

2021-10-21 01:36 UTC, TomHAnderson commented on docs/en/user-guide.rst
> +Install DoctrineODMModule :
`Install DoctrineMongoODMModule :`

2021-10-21 01:36 UTC, TomHAnderson commented on docs/en/user-guide.rst
> +Open ``doctrine-odm-tutorial/configs/application.config.php`` in your
doctrine-odm-tutorial?  That sounds like a very old reference and is certainly out of scope for Laminas.  Just reference `config/application.config.php`

2021-10-21 08:37 UTC, TomHAnderson approved these changes

2021-10-21 15:00 UTC, merged