Remove changelog and updated URL to docs
doctrine/DoctrineMongoODMModule pull request #236
Opened 2021-10-23 12:08 UTC by driehle

This needs the following PR on doctrine-website to be merged first for the docs URL to work:

- https://github.com/doctrine/doctrine-website/pull/421

Removes changelog file, as with `laminas/automatic-release` the changelog is in the release notes of Github releases. Updates the year in the license file.

2021-10-23 23:31 UTC, TomHAnderson requested changes

2021-10-23 23:31 UTC, TomHAnderson commented on README.md
> +The DoctrineMongoODMModule is based on [DoctrineModule](https://github.com/doctrine/DoctrineModule/) and integrates
Change to 

```
The DoctrineMongoODMModule leverages [DoctrineModule](https://github.com/doctrine/DoctrineModule/) and integrates 
Doctrine MongoDB ODM with Laminas quickly and easily. The following features are intended to work out of the box:
```

2021-10-25 13:28 UTC, driehle commented on README.md
> +The DoctrineMongoODMModule is based on [DoctrineModule](https://github.com/doctrine/DoctrineModule/) and integrates
Fixed and squashed in ec05e71

2021-10-25 18:00 UTC, TomHAnderson approved these changes

2021-10-25 18:51 UTC, merged