Move doctrine/persistence to dev dependencies
doctrine/DoctrineMongoODMModule pull request #269
Opened 2022-11-04 13:18 UTC by MidnightDesign

The dependency is not used in production code, only in DoctrineMongoODMModuleTest\Assets\CustomRepositoryFactory.

2022-11-04 14:16 UTC, driehle requested changes
By moving persistence to require-dev, we will automatically allow persistence v3 for this module, as upstream DoctrineModule allows either v2 or v3. Therefore, could you please change it to `^2.4.0 || ^3.0.0`? We will have to ensure that our unit tests run v3, otherwise this change could be harmful for users.

2022-11-04 14:16 UTC, driehle commented on composer.json
> +        "doctrine/persistence": "^2.4.0",
```suggestion
        "doctrine/persistence": "^2.4.0 || ^3.0.0",
```

2022-11-04 15:02 UTC, rieschl approved these changes

2022-11-07 09:44 UTC, driehle approved these changes

2022-11-07 09:44 UTC, merged

2022-11-07 09:46 UTC, driehle commented
I have fixed the issue with PhpStan, which was still present in this PR. Since this PR effectively adds a new feature, i.e. the support for persistence v3, we have to release it as a new minor release, i.e. 4.2.0 and not 4.1.2.

Thank you, @MidnightDesign, for your time and contribution!

2022-11-08 08:40 UTC, MidnightDesign commented
@driehle Would it be possible to release 4.2? We're waiting for this change. Thanks!

2022-11-08 13:02 UTC, driehle commented
I am planning to first get #270 merged before releasing 4.2.0. However, I expect to make a release today or tomorrow.